#!/bin/bash

## Script to run A3 artifact with all A3 tests
## DOES NOT RECEIVE OPTIONS

## Avoid relative paths
JAR=`python -c 'import os.path; print os.path.realpath(os.path.abspath("../L3_T3.jar"))'`

## Run supertest.py with silver compiler
python supertest.py -A3 java -jar $JAR
