#!/bin/bash

## Script to run A2a artifact with all A2a tests
## DOES NOT RECEIVE OPTIONS

## Avoid relative paths
JAR=`python -c 'import os.path; print os.path.realpath(os.path.abspath("../L3_T2.jar"))'`

## Run supertest.py with silver compiler
python supertest.py -A2a java -jar $JAR
