#!/bin/bash

rm -f ../tests/*/positive/L*/*_pp.ob
rm -f ../tests/*/positive/L*/*_lifted.ob
rm -f ../tests/*/positive/L*/*.c
rm -f ../tests/*/positive/L*/*.a
rm -f ../tests/*/positive/L*/*.stdout
rm -f ../tests/*/positive/L*/*.errors

rm -f ../tests/*/negative/*_errors/L*/*_pp.ob
rm -f ../tests/*/negative/*_errors/L*/*.errors
rm -f ../tests/*/negative/*_errors/L*/*_lifted.ob
rm -f ../tests/*/negative/*_errors/L*/*.c

