#!/bin/bash

## To run artefact-specific tests, use the 'A#' option (sub 1, 2a, 2b, 3, 4 or 5 for '#')

if test $# -ne 1
then
    echo 'usage: kiama_tests artefact'
    exit 1
fi    

## Avoid relative paths
KOBC=`python -c 'import os.path; print os.path.realpath(os.path.abspath("../kobc"))'`

## Run supertest.py with Kiama compiler
python supertest.py $@ $KOBC $@
