#!/bin/bash

## Script to run A4 artifact with all A4 tests
## DOES NOT RECEIVE OPTIONS

## Avoid relative paths
JAR=`python -c 'import os.path; print os.path.realpath(os.path.abspath("../L4_T5.jar"))'`

## Run supertest.py with silver compiler
python supertest.py -A4 java -jar $JAR
