#!/bin/bash

## Script to run A1 artifact with all A1 tests
## DOES NOT RECEIVE OPTIONS

## Avoid relative paths
JAR=`python -c 'import os.path; print os.path.realpath(os.path.abspath("../L2_T2.jar"))'`

## Run supertest.py with silver compiler
python supertest.py -A1 java -jar $JAR
